CG5_HEADER = [
    'Survey name',
    'Instrument S/N',
    'Client',
    'Operator',
    'Date',
    'Time',
    'LONG',
    'LAT',
    'ZONE',
    'GMT DIFF.',
    'Gref',
    'Gcal1',
    'TiltxS',
    'TiltyS',
    'TiltxO',
    'TiltyO',
    'Tempco',
    'Drift',
    'DriftTime Start',
    'DriftDate Start',
    'Tide Correction',
    'Cont. Tilt',
    'Auto Rejection',
    'Terrain Corr.',
    'Seismic Filter',
    'Raw Data',
    'LINE',
    'STATION',
    'ALT.',
    'GRAV.',
    'SD.',
    'TILTX',
    'TILTY',
    'TEMP',
    'TIDE',
    'DUR',
    'REJ',
    'TIME',
    'DEC.TIME+DATE',
    'TERRAIN',
    'DATE',
    'MeterType',
    'DataFile',
    'Created',
    'Date_time',
]